import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ✅ Added import for FloatingBackground
import FloatingBackground from "./components/FloatingBackground"; 

import Header from "./components/header";
import Footer from "./components/footer";

// === Fonts Setup ===
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// === Metadata ===
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`} 
        // ✅ Added "relative" so FloatingBackground positions correctly inside body
      >
        {/* ✅ Floating background placed behind all content */}
        <FloatingBackground /> 

        {/* === Main Layout Content === */}
        <Header /> 
        {children}
        <Footer />
      </body>
    </html>
  );
}
